### ISSUE TITLE
Download daily data

### ISSUE THREAD

**Issue by lahirujayakody** [wateraccounting/WAPOROCW#12]
When I try to download daily data using "1_Bulk_download_WaPOR_data" codes, comes below error message

AttributeError: '__WaPOR_API_class' object has no attribute 'Token' (There is no problem with downloading monthly and yearly data).

Thank you

**Comment by trngbich** [comment]
Hi.

Thank you for reporting this error. I have fixed this issue in the last commit (https://github.com/wateraccounting/WAPOROCW/commit/451c6e4be2b081f6c8d07983a9859b03d15d8033)
Please update the repository on your local machine.

**Comment by lahirujayakody** [comment]
> Hi.
> 
> Thank you for reporting this error. I have fixed this issue in the last commit ([451c6e4](https://github.com/wateraccounting/WAPOROCW/commit/451c6e4be2b081f6c8d07983a9859b03d15d8033)) Please update the repository on your local machine.

Thank you
