### ISSUE TITLE
Installation of 'request'pacakage

### ISSUE THREAD

**Issue by mnshrestha** [wateraccounting/WAPOROCW#2]
I have a problem  to install requests package.
Error is 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b13a000e1d07> in <module>
----> 1 import notinstalledpackage

ModuleNotFoundError: No module named 'notinstalledpackage'

**Comment by trngbich** [comment]
This is just an example of Error message if a package is not installed.
If you can run the previous code cell without problem, it means all required packages are installed
